local_win:
  drugmatrix:
        driver: 'PostgreSQL ANSI(x64)'
        server: '10.98.105.92'
        uid: 'ntp_group'
        pwd: 'ntp_group'
        port: 5432
        database: 'drugmatrix'
default:
  dbconnection:
    driver: 'PostgreSQL ODBC Driver(UNICODE)'
    host: '10.98.105.92'
    uid: 'ntp_group'
    pwd: 'ntp_group'
    port: 5432
    database: 'drugmatrix'
 
rsconnect-ntp-dev:
  drugmatrix:
    driver: 'PostgreSQL'
    host: '10.98.105.92'
    uid: 'ntp_group'
    pwd: 'ntp_group'
    port: 5432
    database: 'drugmatrix'
 
rsconnect-ntp-prod:
  dbconnection:
    driver: 'Postgres'
    host: '127.0.0.1'
    uid: 'user'
    pwd: 'pass'
    port: 5432
    database: 'postgres'
